[package]
name = "hsdfiugjhasdifgujhsdkfjg"
version = "0.0.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
license = "MIT/Apache-2.0"

[[bench]]
name = "lol"
harness = false

[dev-dependencies]
rand = "*"
criterion = "0.2"

[dependencies.typenum]
version = "*"
features = ["no_std"]
